### PR TITLE
chore: fix docs url for new non-cloud libraries

### LINKED ISSUE #11193: Broken client library links in newly generated client libraries due to invalid value for `client_documentation`
Several new client libraries had broken documentation links when they were generated using the [bootstrapping container](https://github.com/googleapis/google-cloud-python/tree/main/containers/python-bootstrap-container).

The issue is that the client library documentation links differ depending on whether the client library is for a product which is part of `Google Cloud`. When the client library belongs to `Google Cloud`, the client library documentation will be located at `"https://cloud.google.com/python/docs/reference/<apiName>/latest"`, otherwise it will be located at `"https://googleapis.dev/python/<apiName>/latest"`.

The `client_documentation` value should be populated dynamically instead of hardcoded here:
https://github.com/googleapis/google-cloud-python/blob/a429c434c6847f538b851660b2915abeef33a592/containers/python-bootstrap-container/.repo-metadata.json#L6

### PR DESCRIPTION
**Pull request by parthea**
Fixes #11193 🦕

### CODE REVIEW

File: containers/python-bootstrap-container/entrypoint.sh [hunk 1]
```diff
@@ -101,13 +101,24 @@ DOCS_ROOT_URL=$(jq --arg API_SHORTNAME "$API_SHORTNAME" -r '.apis | to_entries[]
...
 fi
 
 # Update apiProductDocumentation in .repo-metadata.json
-sed -i -e "s|apiProductDocumentation|$DOCS_URL|" "${WORKSPACE_DIR}/${MONO_REPO_NAME}/packages/${FOLDER_NAME}/.repo-metadata.json"
+sed -i -e "s|apiProductDocumentation|$PRODUCT_DOCS_URL|" "${WORKSPACE_DIR}/${MONO_REPO_NAME}/packages/${FOLDER_NAME}/.repo-metadata.json"
+
+# If the API is `cloud`, the docs will be published to `cloud.google.com`.
+# For non-cloud, the docs will be published to `googleapis.dev`.
+if [[ $FOLDER_NAME =~ "cloud" ]]; then
+    CLIENT_DOCS_URL="$(echo https://cloud.google.com/python/docs/reference/$FOLDER_NAME/latest)"
```
Comment (vchudnov-g) [inline containers/python-bootstrap-container/entrypoint.sh:115]: Why do you need the `echo` here? Why not simply
`CLIENT_DOCS_URL="https://cloud.google.com/python/docs/reference/${FOLDER_NAME}/latest"` and similarly below?

Comment (parthea) [reply containers/python-bootstrap-container/entrypoint.sh:115]: Good catch! Opened https://github.com/googleapis/google-cloud-python/pull/11963 to clean up the code.
